### ISSUE TITLE
Could not initialize memory! Exiting...

### ISSUE THREAD

**Issue by ArcaneGit** [Kix48/R6Offline#1]
If I had to guess outdated offsets.

**Comment by Kix48** [comment]
Offsets do need to be updated as of now but that isn't the issue. If you take a look at what will cause that error, you will see a problem is occurring with getting either the process id or the base address. I Recommend you make sure Battleye isn't running because otherwise you won't be able to get the base address.

**Comment by Desparration** [comment]
Could not find file d3dx9.h. How do I find this file, or do i replace the name with something?

**Comment by Kix48** [comment]
You will need to link it. Add $(DXSDK_DIR)Include to the includes in the project settings and $(DXSDK_DIR)Lib\x64 to the libs in the project settings. Otherwise, you need to install DirectX
